import 'package:injectable/injectable.dart';

@lazySingleton
class Constant {
  static const String tocken = "XMCNBVGDTE734BCU65DW";
  static const String amountCurrency = "\$";
  static const String rupeesSymbol = "₹";
  static const String supportNumber1 = "+971528444000";
  static const String supportNumber2 = "+91 9922333639";
  static const String supportNumber3 = "+9120 48649981";

  static const String merchantVpa = "vipstrade@yesbank";
  static const String htmlRegex = "<([A-Za-z][A-Za-z0-9]*)\\b[^>]*>(.*?)</\\1>";
  static const String usdtAddress = "TWHLaq1PBJNRPifvwVjr5Uj1CTrVnRG4Fn";
  static const String bitcoinAddress = "16VZpLkp1gKFSriPF57iNwVxj3JBppkHBo";
  static const String usdtBscAddress =
      "0xc8f0f077e53f86f6c11a59c519f953338fba7f00";
  static const String secureKey = "R6Ke4CVnsp@drjymALXfFgzPbZ5Nu@3GBDckYSMw";
  static const String appName = "CentFX";

  //Finstock Api Secret Key

  static const String testSecretKey = "jvd9W3HA7VK2s2T9bByvTQPAS6bT3CNPL";
  static const String liveSecretKey = "2q4hBsvBxn6ehJqMGUdtmHDdqXaAcCJbv";
  static const String secretKey = liveSecretKey;

  static const String authToken = "a392epl6-e245-4vvm-001a-a7dl963jeb2";

  //app info
  static const String androidPackageName = "com.phoenixfx";
  static const String iOSPackageName = "com.phoenixfx";
  static const String appStoreId = '1596096696';

  //social media
  static const String facebookLink =
      "https://www.facebook.com/AB-Capitals-103685812348294/?ref=page_internal";
  static const String youtubeLink =
      "https://www.youtube.com/channel/UChwddVHZXDZcYIYN0M7LlYg";
  static const String instagramLink =
      "https://www.instagram.com/phoenixfx.ltd/?igshid=MzRlODBiNWFlZA%3D%3D";
  static const String telegramLink = "https://t.me/centfx";
  static const String whatsappLink =
      "https://whatsapp.com/channel/0029VaEu4ig5Ejy5RSfP1d32";
  static const String twitterLink = "";

  static const String applicationType = "ABCAPITAL";

  static const String androidVersion = "AppVersion";
  static const String iOSVersion = "IOSAppVersion";

  static const String playStoreLink =
      "https://play.google.com/store/apps/details?id=com.phoenixfx";

  //images
  static const String logoh = "assets/logo_h.jpg";
  static const String logohtrasparent = "assets/logo_h_transparent.png";
  static const String defaultProfile = "assets/default_profile.png";
  static const String centfxlogo = "assets/centfx_logo.png";

  static const String iOSPlatformLink =
      "https://download.mql5.com/cdn/mobile/mt5/ios?server=CentFx-Live";

  static const androidPlatformLink =
      "https://download.mql5.com/cdn/mobile/mt5/android?server=CentFx-Live";

  static const defaultEconomicCountries = [
    "US",
    "EU",
    "IT",
    "NZ",
    "CH",
    "AU",
    "FR",
    "JP",
    "ZA",
    "TR",
    "CA",
    "DE",
    "MX",
    "ES",
    "GB"
  ];

  Map<String, String> countryNames = {
    "US": "United States",
    "EU": "European Union",
    "IT": "Italy",
    "NZ": "New Zealand",
    "CH": "Switzerland",
    "AU": "Australia",
    "FR": "France",
    "JP": "Japan",
    "ZA": "South Africa",
    "TR": "Turkey",
    "CA": "Canada",
    "DE": "Germany",
    "MX": "Mexico",
    "ES": "Spain",
    "GB": "United Kingdom",
    "AT": "Austria",
    "LT": "Lithuania",
    "BE": "Belgium",
    "LU": "Luxembourg",
    "CY": "Cyprus",
    "NL": "Netherlands",
    "NO": "Norway",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "EE": "Estonia",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "RU": "Russia",
    "RS": "Serbia",
    "SK": "Slovakia",
    "FI": "Finland",
    "GR": "Greece",
    "HU": "Hungary",
    "IS": "Iceland",
    "IE": "Ireland",
    "UA": "Ukraine",
    "SE": "Sweden",
    "LV": "Latvia",
    "AO": "Angola",
    "BH": "Bahrain",
    "BW": "Botswana",
    "NG": "Nigeria",
    "OM": "Oman",
    "QA": "Qatar",
    "RW": "Rwanda",
    "SA": "Saudi Arabia",
    "SC": "Seychelles",
    "EG": "Egypt",
    "ET": "Ethiopia",
    "GH": "Ghana",
    "IL": "Israel",
    "KE": "Kenya",
    "KW": "Kuwait",
    "MW": "Malawi",
    "MU": "Mauritius",
    "LK": "Sri Lanka",
    "KR": "South Korea",
    "VN": "Vietnam",
    "TH": "Thailand",
    "TW": "Taiwan",
    "ID": "Indonesia",
    "IN": "India",
    "SG": "Singapore",
    "PH": "Philippines",
    "HK": "Hong Kong",
    "BD": "Bangladesh",
    "CN": "China",
    "PK": "Pakistan",
    "MY": "Malaysia",
    "CO": "Colombia",
    "VE": "Venezuela",
    "CL": "Chile",
    "BR": "Brazil",
    "PE": "Peru",
    "AR": "Argentina",
    "NA": "Namibia",
    "ZW": "Zimbabwe",
    "ZM": "Zambia",
    "MZ": "Mozambique",
    "MA": "Morocco",
    "AE": "United Arab Emirates",
    "UG": "Uganda",
  };

  static const Map<String, String> countryCode = {
    "Afghanistan": "AF",
    "Albania": "AL",
    "Algeria": "DZ",
    "American Samoa": "AS",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antarctica": "AQ",
    "Antigua and Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Aruba": "AW",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermuda": "BM",
    "Bhutan": "BT",
    "Bolivia": "BO",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Bouvet Island": "BV",
    "Brazil": "BR",
    "British Indian Ocean Territory": "IO",
    "Brunei Darussalam": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Cape Verde": "CV",
    "Cayman Islands": "KY",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Christmas Island": "CX",
    "Cocos (Keeling) Islands": "CC",
    "Colombia": "CO",
    "Comoros": "KM",
    "Congo": "CG",
    "Congo, the Democratic Republic of the": "CD",
    "Cook Islands": "CK",
    "Costa Rica": "CR",
    "Cote D'Ivoire": "CI",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Ethiopia": "ET",
    "Falkland Islands (Malvinas)": "FK",
    "Faroe Islands": "FO",
    "Fiji": "FJ",
    "Finland": "FI",
    "France": "FR",
    "French Guiana": "GF",
    "French Polynesia": "PF",
    "French Southern Territories": "TF",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Greece": "GR",
    "Greenland": "GL",
    "Grenada": "GD",
    "Guadeloupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Heard Island and Mcdonald Islands": "HM",
    "Holy See (Vatican City State)": "VA",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran, Islamic Republic of": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KI",
    "Korea, Democratic People's Republic of": "KP",
    "Korea, Republic of": "KR",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Lao People's Democratic Republic": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libyan Arab Jamahiriya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Macao": "MO",
    "Macedonia, the Former Yugoslav Republic of": "MK",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marshall Islands": "MH",
    "Martinique": "MQ",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mayotte": "YT",
    "Mexico": "MX",
    "Micronesia, Federated States of": "FM",
    "Moldova, Republic of": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montserrat": "MS",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Netherlands": "NL",
    "Netherlands Antilles": "AN",
    "New Caledonia": "NC",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "Niue": "NU",
    "Norfolk Island": "NF",
    "Northern Mariana Islands": "MP",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palau": "PW",
    "Palestinian Territory, Occupied": "PS",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Pitcairn": "PN",
    "Poland": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Qatar": "QA",
    "Reunion": "RE",
    "Romania": "RO",
    "Russian Federation": "RU",
    "Rwanda": "RW",
    "Saint Helena": "SH",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Pierre and Miquelon": "PM",
    "Saint Vincent and the Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia and Montenegro": "CS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Georgia and the South Sandwich Islands": "GS",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Svalbard and Jan Mayen": "SJ",
    "Swaziland": "SZ",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syrian Arab Republic": "SY",
    "Taiwan, Province of China": "TW",
    "Tajikistan": "TJ",
    "Tanzania, United Republic of": "TZ",
    "Thailand": "TH",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Turks and Caicos Islands": "TC",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "United States Minor Outlying Islands": "UM",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Venezuela": "VE",
    "Viet Nam": "VN",
    "Virgin Islands, British": "VG",
    "Virgin Islands, U.s.": "VI",
    "Wallis and Futuna": "WF",
    "Western Sahara": "EH",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW",
  };

  static const Map<String, String> countriesData = {
    "Afghanistan": "+93",
    "Albania": "+355",
    "Algeria": "+213",
    "American Samoa": "+1",
    "Andorra": "+376",
    "Angola": "+244",
    "Anguilla": "+1",
    "Antarctica": "+672",
    "Antigua and Barbuda": "+1",
    "Argentina": "+54",
    "Armenia": "+374",
    "Aruba": "+297",
    "Australia": "+61",
    "Austria": "+43",
    "Azerbaijan": "+994",
    "Bahamas": "+1",
    "Bahrain": "+973",
    "Bangladesh": "+880",
    "Barbados": "+1",
    "Belarus": "+375",
    "Belgium": "+32",
    "Belize": "+501",
    "Benin": "+229",
    "Bermuda": "+1",
    "Bhutan": "+975",
    "Bolivia": "+591",
    "Bosnia and Herzegovina": "+387",
    "Botswana": "+267",
    "Bouvet Island": "",
    "Brazil": "+55",
    "British Indian Ocean Territory": "+246",
    "Brunei Darussalam": "+673",
    "Bulgaria": "+359",
    "Burkina Faso": "+226",
    "Burundi": "+257",
    "Cambodia": "+855",
    "Cameroon": "+237",
    "Canada": "+1",
    "Cape Verde": "+238",
    "Cayman Islands": "+1",
    "Central African Republic": "+236",
    "Chad": "+235",
    "Chile": "+56",
    "China": "+86",
    "Christmas Island": "+61",
    "Cocos (Keeling) Islands": "+61",
    "Colombia": "+57",
    "Comoros": "+269",
    "Congo": "+242",
    "Congo, the Democratic Republic of the": "+243",
    "Cook Islands": "+682",
    "Costa Rica": "+506",
    "Cote D'Ivoire": "+225",
    "Croatia": "+385",
    "Cuba": "+53",
    "Cyprus": "+357",
    "Czech Republic": "+420",
    "Denmark": "+45",
    "Djibouti": "+253",
    "Dominica": "+1",
    "Dominican Republic": "+1",
    "Ecuador": "+593",
    "Egypt": "+20",
    "El Salvador": "+503",
    "Equatorial Guinea": "+240",
    "Eritrea": "+291",
    "Estonia": "+372",
    "Ethiopia": "+251",
    "Falkland Islands (Malvinas)": "+500",
    "Faroe Islands": "+298",
    "Fiji": "+679",
    "Finland": "+358",
    "France": "+33",
    "French Guiana": "+594",
    "French Polynesia": "+689",
    "French Southern Territories": "",
    "Gabon": "+241",
    "Gambia": "+220",
    "Georgia": "+995",
    "Germany": "+49",
    "Ghana": "+233",
    "Gibraltar": "+350",
    "Greece": "+30",
    "Greenland": "+299",
    "Grenada": "+1",
    "Guadeloupe": "+590",
    "Guam": "+1",
    "Guatemala": "+502",
    "Guinea": "+224",
    "Guinea-Bissau": "+245",
    "Guyana": "+592",
    "Haiti": "+509",
    "Heard Island and Mcdonald Islands": "",
    "Holy See (Vatican City State)": "+39",
    "Honduras": "+504",
    "Hong Kong": "+852",
    "Hungary": "+36",
    "Iceland": "+354",
    "India": "+91",
    "Indonesia": "+62",
    "Iran, Islamic Republic of": "+98",
    "Iraq": "+964",
    "Ireland": "+353",
    "Israel": "+972",
    "Italy": "+39",
    "Jamaica": "+1",
    "Japan": "+81",
    "Jordan": "+962",
    "Kazakhstan": "+7",
    "Kenya": "+254",
    "Kiribati": "+686",
    "Korea, Democratic People's Republic of": "+85",
    "Korea, Republic of": "+82",
    "Kuwait": "+965",
    "Kyrgyzstan": "+996",
    "Lao People's Democratic Republic": "+856",
    "Latvia": "+371",
    "Lebanon": "+961",
    "Lesotho": "+266",
    "Liberia": "+231",
    "Libyan Arab Jamahiriya": "+218",
    "Liechtenstein": "+423",
    "Lithuania": "+370",
    "Luxembourg": "+352",
    "Macao": "+853",
    "Macedonia, the Former Yugoslav Republic of": "+38",
    "Madagascar": "+261",
    "Malawi": "+265",
    "Malaysia": "+60",
    "Maldives": "+960",
    "Mali": "+223",
    "Malta": "+356",
    "Marshall Islands": "+692",
    "Martinique": "+596",
    "Mauritania": "+222",
    "Mauritius": "+230",
    "Mayotte": "+262",
    "Mexico": "+52",
    "Micronesia, Federated States of": "+691",
    "Moldova, Republic of": "+373",
    "Monaco": "+377",
    "Mongolia": "+976",
    "Montserrat": "+1",
    "Morocco": "+212",
    "Mozambique": "+258",
    "Myanmar": "+95",
    "Namibia": "+264",
    "Nauru": "+674",
    "Nepal": "+977",
    "Netherlands": "+31",
    "Netherlands Antilles": "+599",
    "New Caledonia": "+687",
    "New Zealand": "+64",
    "Nicaragua": "+505",
    "Niger": "+227",
    "Nigeria": "+234",
    "Niue": "+683",
    "Norfolk Island": "+672",
    "Northern Mariana Islands": "+1",
    "Norway": "+47",
    "Oman": "+968",
    "Pakistan": "+92",
    "Palau": "+680",
    "Palestinian Territory, Occupied": "+970",
    "Panama": "+507",
    "Papua New Guinea": "+675",
    "Paraguay": "+595",
    "Peru": "+51",
    "Philippines": "+63",
    "Pitcairn": "",
    "Poland": "+48",
    "Portugal": "+351",
    "Puerto Rico": "+1",
    "Qatar": "+974",
    "Reunion": "+262",
    "Romania": "+40",
    "Russian Federation": "+7",
    "Rwanda": "+250",
    "Saint Helena": "+290",
    "Saint Kitts and Nevis": "+1",
    "Saint Lucia": "+1",
    "Saint Pierre and Miquelon": "+508",
    "Saint Vincent and the Grenadines": "+1",
    "Samoa": "+685",
    "San Marino": "+378",
    "Sao Tome and Principe": "+239",
    "Saudi Arabia": "+966",
    "Senegal": "+221",
    "Serbia and Montenegro": "",
    "Seychelles": "+248",
    "Sierra Leone": "+232",
    "Singapore": "+65",
    "Slovakia": "+421",
    "Slovenia": "+386",
    "Solomon Islands": "+677",
    "Somalia": "+252",
    "South Africa": "+27",
    "South Georgia and the South Sandwich Islands": "",
    "Spain": "+34",
    "Sri Lanka": "+94",
    "Sudan": "+249",
    "Suriname": "+597",
    "Svalbard and Jan Mayen": "+47",
    "Swaziland": "+268",
    "Sweden": "+46",
    "Switzerland": "+41",
    "Syrian Arab Republic": "+963",
    "Taiwan, Province of China": "+886",
    "Tajikistan": "+992",
    "Tanzania, United Republic of": "+255",
    "Thailand": "+66",
    "Timor-Leste": "+670",
    "Togo": "+228",
    "Tokelau": "+690",
    "Tonga": "+676",
    "Trinidad and Tobago": "+1",
    "Tunisia": "+216",
    "Turkey": "+90",
    "Turkmenistan": "+993",
    "Turks and Caicos Islands": "+1",
    "Tuvalu": "+688",
    "Uganda": "+256",
    "Ukraine": "+380",
    "United Arab Emirates": "+971",
    "United Kingdom": "+44",
    "United States": "+1",
    "United States Minor Outlying Islands": "",
    "Uruguay": "+598",
    "Uzbekistan": "+998",
    "Vanuatu": "+678",
    "Venezuela": "+58",
    "Viet Nam": "+84",
    "Virgin Islands, British": "+1",
    "Virgin Islands, U.s.": "+1",
    "Wallis and Futuna": "+681",
    "Western Sahara": "+212",
    "Yemen": "+967",
    "Zambia": "+260",
    "Zimbabwe": "+263",
  };

  static const coindData = [
    {"crypto": "btc", "title": "Bitcoin (Bitcoin)"},
    {"crypto": "ethereum", "title": "Ethereum (Ethereum)"},
    {"crypto": "litecoin", "title": "Litecoin (Litecoin)"},
    {"crypto": "dash", "title": "Dash (Dash)"},
    {"crypto": "bitcoincash", "title": "Bitcoin Cash (Bitcoin Cash)"},
    {"crypto": "monero", "title": "Monero (Monero)"},
    {"crypto": "ripple", "title": "Ripple (Ripple)"},
    {"crypto": "dogecoin", "title": "Dogecoin (Dogechain)"},
    {"crypto": "zcash", "title": "Zcash (Zcash)"},
    {"crypto": "steller", "title": "Steller (Stellar)"},
    {"crypto": "tron", "title": "TRON (TRON)"},
    {"crypto": "binancecoin", "title": "Binance Coin (Binance Smart Chain)"},
    {"crypto": "omgnetwork", "title": "OMG Network (Ethereum)"},
    {"crypto": "usdcoin", "title": "USD Coin (Ethereum)"},
    {"crypto": "tetherus", "title": "TetherUS (Ethereum)"},
    {"crypto": "paxdollar", "title": "Pax Dollar (Ethereum)"},
    {"crypto": "trueusd", "title": "TrueUSD (Ethereum)"},
    {"crypto": "binancechain", "title": "Binance Coin (Binance Chain)"},
    {"crypto": "tetherusbsc", "title": "TetherUS (Binance Smart Chain)"},
    {"crypto": "binanceusd", "title": "Binance USD (Ethereum)"},
    {"crypto": "binanceusdbsc", "title": "Binance USD (Binance Smart Chain)"},
    {"crypto": "usdcoinbsc", "title": "USD Coin (Binance Smart Chain)"},
    {"crypto": "paxdollarbsc", "title": "Pax Dollar (Binance Smart Chain)"},
    {"crypto": "usdcointron", "title": "USD Coin (TRON)"},
    {"crypto": "tetherustron", "title": "TetherUS (TRON)"}
  ];

  static const ticketCategory = [
    "Trading Operations",
    "Non-trading Operations",
    "Account Opening",
    "KYC",
    "Deposit",
    "Withdrawals"
  ];

  static const ticketPriority = ["Low", "Medium", "High"];
}

enum WithdrawType { withdraw, usdtWithdraw, ibWithdraw }
